# Generated by Django 5.1.6 on 2025-02-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API1',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
