services:
  web:
    build: . 
    command: python3 app.py
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    environment:
      - mongodb+srv://kris6uu7:chessChess2*2*@krishanfil.1vix8.mongodb.net/?retryWrites=true&w=majority&appName=krishanfil