# Generated by Django 5.1.6 on 2025-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackHoles',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mass', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
