# Generated by Django 5.1.6 on 2025-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackHoleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackhole',
            name='id',
        ),
        migrations.AlterField(
            model_name='blackhole',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
