# Generated by Django 5.1.6 on 2025-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackHoleApp', '0002_remove_blackhole_id_alter_blackhole_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackhole',
            name='Bid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blackhole',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
