version: '3.8'

networks:
  middleware_prj_network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'fil'
      MYSQL_ROOT_PASSWORD: 'chessChess2*2*'
      MYSQL_USER: 'root'  # Ensure root user access
      MYSQL_PASSWORD: 'chessChess2*2*'
    ports:
      - "3306:3306"  # Use port 3306 to match settings.py
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pchessChess2*2* || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    platform: linux/x86_64
    networks:
      - middleware_prj_network

  web:
    build: .
    container_name: djangonew
    restart: always
    command: >
      sh -c "python middleware_prj/manage.py migrate &&
             python middleware_prj/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=localhost  # Match settings.py (localhost instead of db)
      - MYSQL_NAME=fil
      - MYSQL_USER=root
      - MYSQL_PASSWORD=chessChess2*2*
      - DJANGO_SETTINGS_MODULE=middleware_prj.settings
    networks:
      - middleware_prj_network

volumes:
  mysql_data:
