# Generated by Django 5.1.6 on 2025-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='managed_by',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
